title: SuHo Yu Portfolio
description: >-
  Systems Engineer | UAM & eVTOL | Battery Systems | Government R&D | Flight-Proven Projects
  Specialized in integrated aircraft systems, certification, and high-voltage energy architecture.

baseurl: "/portfolYOU"  # 또는 "" ← 사용 중인 GitHub Pages 유형에 따라 선택

repository: yoosuho/portfolYOU
remote_theme: yousinix/portfolYOU
open_new_tab: true

plugins:
  - jemoji

nav_exclude:
  - pages/tags.html
  - pages/404.html
  - documentation/partials/**

author:
  name: SuHo Yu
  image: assets/me.jpg
  email: yoosuho97@gmail.com
  github: yoosuho
  linkedin: suho-yu
  youtube: jenk5109

permalink: /blog/:title

collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:
    output: true

exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
