### Site Settings ###
title               : SuHo Yu
description         : >-
                      SuHo :Portfolio: into code,
                      use tabs over spaces
                      and never broke production.
baseurl: ""
url: "https://www.suhoyu.com"
repository          : yousinix/portfolYOU      # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
#  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/uam.html
  - pages/uam.md 
  - pages/plane.md   
  - pages/uam2.md     
  - pages/drone.md     
  - pages/250wh.md     
  - pages/Abda.md     
  - pages/AI.md     
  - pages/CD40.md     
  - pages/CD200.md     
  - pages/engl.md     
  - pages/gr.md     
  - pages/gs.md     
  - pages/ka.md     
  - pages/lig.md     
  - pages/mvus.md     
  - pages/ups.md     
  - pages/gim.md     
  - pages/kuam.md       
  
#  - documentation/partials/**                           # For Documentation Only

nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects
  - title: "blog"
    url: /blog
  - title: "About"
    url: /about
  - title: "elements"
    url: /elements   
  - title: "docs"
    url: /docs
  
### Author Info ###
author:
  name              : SuHo Yu
  image             : https://i.imgur.com/uyDNQnn.jpg
  behance           : your_username
# dribbble          : your_username
  email             : yoosuho97@mail.com
# facebook          : your_username
  github            : yoosuho
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : suho-yu
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
  youtube           : jenk5109
# keybase           : your_username





### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only
  blog:
    output: true
    permalink: /blog/:name
    
### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "page"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: "page"                                 # Set to true to enable disqus comments
  - scope:
      path: ""
      type: "blog"
    values:
      comments: "default"


# 아래 줄 추가
head_custom: head-custom.html

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
